-- Create playlists table
CREATE TABLE public.playlists (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  duration INTEGER NOT NULL DEFAULT 60, -- duration in minutes
  color TEXT NOT NULL DEFAULT 'bg-blue-500',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create scheduled_items table
CREATE TABLE public.scheduled_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  playlist_id BIGINT NOT NULL REFERENCES public.playlists(id) ON DELETE CASCADE,
  day TEXT NOT NULL,
  hour INTEGER NOT NULL CHECK (hour >= 0 AND hour <= 23),
  duration INTEGER NOT NULL, -- duration in minutes
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.playlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_items ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for public access (adjust based on your auth requirements)
CREATE POLICY "Allow all operations on playlists" ON public.playlists FOR ALL USING (true);
CREATE POLICY "Allow all operations on scheduled_items" ON public.scheduled_items FOR ALL USING (true);

-- Insert sample playlists
INSERT INTO public.playlists (name, duration, color) VALUES 
('Morning Energy', 120, 'bg-yellow-500'),
('Focus Session', 90, 'bg-blue-500'),
('Chill Vibes', 60, 'bg-green-500'),
('Workout Mix', 45, 'bg-red-500'),
('Evening Wind Down', 180, 'bg-purple-500');

-- Create function to update timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for automatic timestamp updates
CREATE TRIGGER update_playlists_updated_at
    BEFORE UPDATE ON public.playlists
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_scheduled_items_updated_at
    BEFORE UPDATE ON public.scheduled_items
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();